enabled: true
external_in_new_tab: false
append_site_title: true
logo_height: h-6
custom_logo:
  user/assets/typhoon/dharavi-org_logo.svg:
    name: dharavi-org_logo.svg
    full_path: dharavi-org_logo.svg
    type: image/svg+xml
    size: 6520
    path: user/assets/typhoon/dharavi-org_logo.svg
custom_logo_strip_svg_style: true
custom_favicon:
  user/assets/typhoon/dharavi-org_single.svg:
    name: dharavi-org_single.svg
    full_path: dharavi-org_single.svg
    type: image/svg+xml
    size: 2237
    path: user/assets/typhoon/dharavi-org_single.svg
colors:
  text_style: 'text-gray-600 dark:text-gray-400'
  brightness_lighter: 20
  brightness_darker: 20
  primary: '#3893F8'
appearance:
  theme: dark
  selector: true
  storage: true
  cookie: true
body_classes: null
section_classes: 'bg-white dark:bg-gray-900 py-8 md:py-24'
wrapper_spacing: 'xl:container xl:mx-auto md:px-6 px-4'
menu:
  primary_location: header
  primary_menu_levels: 3
  mobile_nav: true
  icon_classes: 'hidden md:inline-block h-4 w-4 opacity-75 mr-1'
  login:
    enabled: true
    icon: tabler/user.svg
    logged_in_display: username
    logout_icon: tabler/logout.svg
  langswitcher:
    enabled: false
    icon: tabler/world.svg
header_bar:
  background: auto
  custom_style: 'linear-gradient(90deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.4) 100%)'
  text: auto
  fixed: false
  height: h-16
hero:
  display: true
  overlay: dark
  overlay_direction: right
  alignment: left
  image: 'theme://images/headers/sea-and-sky.jpg'
  custom: '#3C4043'
  padding: 'pt-32 md:pt-40 lg:pt-48 xl:pt-56 pb-16 md:pb-20 lg:pb-24 xl:pb-32'
  image_alignment: object-center
  overlay_gradient:
    - '0.8'
    - '0.3'
footer:
  menu_enabled: true
  menu:
    -
      label: home
      link: /
      newtab: false
    -
      label: urbz.net
      link: 'https://urbz.net/'
      newtab: true
    -
      label: nyuad.io
      link: 'https://nyuad.io/'
      newtab: true
  social_enabled: true
  social:
    -
      network: github
      link: 'https://github.com/dharavi-org'
      newtab: true
  copyright: "Maintained by [urbz](https://urbz.net?classes=hover:text-primary,font-bold).\nCrafted by the students of [EfSI 2023](https://nyuad.io?classes=hover:text-primary,font-bold)."
notices:
  -
    content: 'An example **critical** message that should show up on homepage only'
    enabled: false
    route: /
    type: critical
    learn_more_link: 'https://getgrav.org'
  -
    content: 'An example **note** that should appear on all pages! No link..'
    enabled: false
    route: null
    type: note
    learn_more_link: null
footer_page_route: null
notices_page_route: null
