title: dharavi.org
default_lang: en
author:
  name: Admin
  email: admin@dharavi.org
taxonomies:
  - category
  - tag
metadata:
  description: 'dharavi.org seeks to launch a platform that fosters discussion and exchange, in order to develop a comprehensive strategy and theory that challenges traditional notions of urban development. Framed as a journal in the pursuit of promoting a radical new approach to urban development in Dharavi, the discourse around innovative and transformative ideas is paramount. Our goal is to introduce fresh and dynamic home grown concepts that break from convention, in both the Global South and North. We believe that this is a moment for visionary thinking and pushing boundaries in order to pave the way for real and lasting change.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
